### GET list of uploaded files 
GET http://localhost:3000/files

### GET - download file
GET http://localhost:3000/files/kot.jpg

### POST - upload file
POST http://localhost:3000/files/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="cat-laptop-banner.jpg"
Content-Type: image/jpg

< ./cat-laptop-banner.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### DELETE - download file
DELETE http://localhost:3000/files/cat-laptop-banner.jpg

### POST - upload file to Google Cloud Storage
POST http://localhost:3000/gcs/files/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="cat-laptop-banner.jpg"
Content-Type: image/jpg

< ./cat-laptop-banner.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### GET list of files uploaded to google cloud storage 
GET http://localhost:3000/gcs/files

### GET file uploaded to google cloud storage 
GET http://localhost:3000/gcs/files/cat-laptop-banner.jpg
